version: '3.9'

services:
  web-ext:
    build: "node:18-alpine"
    working_dir: /web-ext
    volumes:
      - ./:/web-ext:ro
      - ./build:/web-ext/build:rw
    environment:
      - WEB_EXT_AS_NEEDED=true #https://extensionworkshop.com/documentation/develop/web-ext-command-reference/
    command: "npm run build"