version: '3.9'

services:
  web-ext:
    build:
      context: .
      dockerfile: Dockerfile
      target: base

    working_dir: /app

    volumes:
      - ./src:/app/src:ro
      - ./build:/app/build:rw

    command: "npm run build"
